# Generated by Django 6.0.1 on 2026-02-13 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGeneric',
            fields=[
                ('fdc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('food_category', models.TextField(null=True)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'app"."food_generic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.TextField()),
                ('quantity_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('eaten_at', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.foodgeneric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
